import type { Report, Severity } from "../model.js";
import { countChanges, describeChange, fileTitle, tags, versions } from "./util.js";

const ICON: Record<Severity, string> = { high: "🔴", medium: "🟠", low: "🔵", info: "⚪" };

const esc = (s: string) => s.replace(/\|/g, "\\|");

export function renderMarkdown(report: Report, limit = 50): string {
  const out: string[] = ["## 🔒 lockdiff", ""];
  if (report.files.length === 0) {
    out.push("No lockfile changes.", "");
    return out.join("\n");
  }
  out.push(`\`${report.base}\` → \`${report.head}\``, "");
  for (const f of report.files) {
    const n = countChanges(f.changes);
    out.push(`### \`${fileTitle(f)}\``, "");
    out.push(
      `**+${n.added}** added · **−${n.removed}** removed · **↑${n.upgraded}** upgraded · **↓${n.downgraded}** downgraded${n.modified ? ` · **≠${n.modified}** modified in place` : ""}`,
      "",
    );
    if (f.findings.length === 0) {
      out.push("✅ No risk signals.", "");
    } else {
      out.push("| | Package | Finding | Rule |", "|---|---|---|---|");
      for (const x of f.findings.slice(0, limit)) {
        out.push(
          `| ${ICON[x.severity]} ${x.severity} | \`${esc(x.name)}\` | ${esc(x.message)}${x.detail ? `<br><sub>${esc(x.detail)}</sub>` : ""} | \`${x.rule}\` |`,
        );
      }
      if (f.findings.length > limit) out.push("", `_…and ${f.findings.length - limit} more._`);
      out.push("");
    }
    const detail = (title: string, rows: string[]) => {
      if (rows.length === 0) return;
      out.push(`<details><summary>${title} (${rows.length})</summary>`, "");
      for (const r of rows.slice(0, limit)) out.push(`- ${r}`);
      if (rows.length > limit) out.push(`- _…and ${rows.length - limit} more_`);
      out.push("", "</details>", "");
    };
    detail(
      "Added",
      f.changes
        .filter((c) => c.kind === "added")
        .map((c) => {
          const t = c.to[0] ? tags(c.to[0]) : [];
          return `\`${c.name}\` ${versions(c.to)}${t.length ? ` _(${t.join(", ")})_` : ""}`;
        }),
    );
    detail(
      "Removed",
      f.changes.filter((c) => c.kind === "removed").map((c) => `\`${c.name}\` ${versions(c.from)}`),
    );
    detail(
      "Changed",
      f.changes
        .filter((c) => c.kind === "bumped" || c.kind === "multi")
        .map(
          (c) =>
            `\`${c.name}\` ${describeChange(c).slice(c.name.length + 1)}${c.bump && c.bump !== "other" ? ` _(${c.bump})_` : ""}`,
        ),
    );
    detail(
      "Modified in place",
      f.changes.filter((c) => c.kind === "modified").map((c) => `\`${c.name}\` ${versions(c.to)}`),
    );
  }
  out.push(
    "<sub>Generated by [lockdiff](https://github.com/Nithinfgs/lockdiff). Signals are heuristics, not verdicts.</sub>",
    "",
  );
  return out.join("\n");
}
